### ISSUE TITLE
Stub out an accessibility section within the docs section

### ISSUE THREAD

**Issue by erichuffman** [CivicActions/FE-resource-library#20]
Focus of content should be on documenting working samples of testing workflows within a Drupal theme, or app, etc.

Related content: https://accessibility.civicactions.com/playbook/roles#front-end-engineer--software-engineer

**Comment by cfbauer** [comment]
- Social media icons (example from @mgifford )
- https://codepen.io/mgifford-the-typescripter/pen/zYjygjL
- https://www.accessible-social.com/

**Comment by erichuffman** [comment]
Completed in https://github.com/CivicActions/FE-resource-library/pull/25
