### ISSUE TITLE
Deploy story book and document how to update

### ISSUE THREAD

**Issue by dgading** [CivicActions/FE-resource-library#4]
We need to be able to see the new Storybook instance on the repo. Using something like `gh-pages` we need to come up with a way process to keep the Storybook instance fresh.

**Comment by alex9000** [comment]
https://dev.to/kouts/deploy-storybook-to-github-pages-3bij

**Comment by cfbauer** [comment]
Seemed like @dgading was leaning towards gh-pages and I found this documentation which uses it:

https://budiirawan.com/how-to-publish-storybook-github-pages/

**Comment by cfbauer** [comment]
### Summary of that documentation:


1. Create gh-pages branch
2. Set GitHubg pages to use that branch as the source in the GitHub settings
3. Create a `.github/workflows/storybook.yml` file that looks like this:
`name: Storybook
on:
  push:
    branches:
      - main # if any push happens on branch `main`, run this workflow. You could also add `paths` to detect changes in specific folder

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install and Build
        run: |
          npm ci
          npm run build-storybook

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          branch: gh-pages
          folder: storybook-static # output folder from `npm run build-storybook``

4. Any push to `main` branch should trigger the deployment

**Comment by erichuffman** [comment]
`storybook.yml` file added to the `.github/workflows` directory, which triggers a build of storybook, and push to gh-pages branch anytime there's a merge into `main` branch. Closing issue.
